### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework4G5#1]
I found this. Hope it is helpful.

If you find any other useful resource please post it here

You can learn more about developing GitHub Actions tasks in the GitHub Actions documentation: https://docs.github.com/en/actions

**Comment by uarif** [comment]
Thank you, yes, we will definitely share.

**Comment by reshnashrestha** [comment]
@yasmensarhan27 Can you explain on how we are going to implement github action for our homework ?

**Comment by tirthbha** [comment]
@yasmensarhan27 Thank you for your help.
