### ISSUE TITLE
Maintainer?

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework4G5#2]
@urif You want be a maintainer?

**Comment by uarif** [comment]
@tirthbha I am fine with whatever you want. If you want to be a maintainer, its fine, If you want me to be a maintainer, Okay I will. I am fine with both. 
Thanks for asking, BTW.

**Comment by tirthbha** [comment]
@uarif Great! You can then request to be a maintainer to the prof.

**Comment by UriF** [comment]
Thank you.  NOT NOW

**Comment by uarif** [comment]
> @uarif Great! You can then request to be a maintainer to the prof.

Please make sure, The other person, you have mentioned in the first place is not me. Do not mention that person again @tirthbha. My username is. uarif. Thank you.

**Comment by tirthbha** [comment]
@uarif Oh Im sorry for that, I thought that's you.

**Comment by tirthbha** [comment]
Done
