### ISSUE TITLE
Github work flow

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework4G5#25]
How did you create workflow? Did you use the same code that Dr. Tim suggested? Your help is truly appreciated. I really do not understand the hw.

**Comment by reshnashrestha** [comment]
@sharmistharanit What professor provided is an example of github action/ workflow. For our homework, we need to create new workflow in .yml file for the previous hw code which we are going to do in this hw.
the workflow varies according to the code.
