### ISSUE TITLE
Existing solution!

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework4G5#3]
Which existing solution (from HW2 or HW3) are we going to apply for this task?

**Comment by reshnashrestha** [comment]
Yeah, same question. So for this we are not considering the first hw. right ?

**Comment by tirthbha** [comment]
@tirthbha Yeah, you are right, we are not considering HW1 for this task.
We are going to choose HW2 i.e., different implementations (For Loops, NumPy Built-in Functions and , NumPy Einstein Notation Function) for matrix multiplication and dot product operations in Python for our task. What about you?
