### ISSUE TITLE
Milestone issue

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework4G5#31]
@uarif Can you please add some more milestones, at least one more. I think one of the existing milestone is not working.
Moreover, we need to create 10 new labels, overall. Please go for that too.

**Comment by reshnashrestha** [comment]
I guess there is confusion regarding new labels. 
I clarified with the professor that the 10 labels are required but not all 10 need to be new. For example, there are 9 default labels, you can use them and in case of necessity, you can add new labels. But not hard and fast 10 new labels are required.

**Comment by uarif** [comment]
Okay. Thank yo both
