### ISSUE TITLE
HW Question

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework4G5#5]
What exactly do we have to do for our hw? If you guys understand this please let us know.

**Comment by reshnashrestha** [comment]
I am confused about the process we need to follow. Let's hope we will figure it out soon. I checked and it seems nobody has started to work on the main task.

**Comment by tirthbha** [comment]
@sharmistharanit  @reshnashrestha 
Basically, we will do the following steps for this task, if I were not wrong:

       1) Initialize GitHub Actions by creating a .yml file within .github/workflows in the repository.
       2)  Define Workflow Triggers by specifying events like  push or pull request to the main branch that initiate the workflow, which  includes
            Check out the repository.
            Set up a Python environment.
            Install necessary Python packages: numpy, matplotlib, pytest, flake8.
            Perform linting using flake8.
            Run unit tests with pytest.
        3) Finally, the Documentation part, where we will write instructions detailing the process of creating and configuring the   GitHub Actions workflow.

**Comment by sharmistharanit** [comment]
Where do I create workflow yml file in my repository? @tirthbha

**Comment by reshnashrestha** [comment]
@sharmistharanit you can create workflow in git hub actions.

**Comment by tirthbha** [comment]
@sharmistharanit You can create workflow file to the directory .github/workflows/
