### ISSUE TITLE
Unable to merge, 

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework4G5#53]
Hello, I am trying to merge from my forked -branched repository to the main repository, but I am unable to merge,
The message can be seen in the attached screenshot. What could be the possible issue? BTW, I am the maintainer of the repository.
Your help is appreciated. Thank you,  @laserlab @tirthbha 
<img width="954" alt="Screenshot 2023-10-16 at 8 55 35 PM" src="https://github.com/ubsuny/23-Homework4G5/assets/13534352/38eb660f-c732-4976-87f7-a519f17048de">

**Comment by tirthbha** [comment]
@uarif To merge the pull request, simply click on the "Create pull request" button (which you've circled in the screenshot).

**Comment by reshnashrestha** [comment]
@tirthbha I don't think that is working in this case.

**Comment by laserlab** [comment]
there is no title and no description

**Comment by uarif** [comment]
Yes, I know, but that is not working @tirthbha.

**Comment by uarif** [comment]
Okay, Yes, now it wokred. thank you for checking. I didn't pay attention before. @laserlab.
Thank you gyus, @tirthbha @reshnashrestha
