### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework4G5#64]
Hi @tirthbha which code in our repository we have to check for any potential changes made?

**Comment by tirthbha** [comment]
@uarif  plot_log_matrix_multiplication.py is the algorithm.

**Comment by uarif** [comment]
@tirthbha , I think, its not just to look at both codes and find what's changed. As you can see the workflow, I have added a changelog file, It's something to do with that but couldn't figure that out yet.

**Comment by uarif** [comment]
> @uarif plot_log_matrix_multiplication.py is the algorithm.

Thanks
