### ISSUE TITLE
Task Partition

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework4G5#9]
@uarif How to divide our jobs among us? Let's discuss.

**Comment by uarif** [comment]
I guess, one person should do the algorithm and one person should do the documentation this time, right? @tirthbha

**Comment by tirthbha** [comment]
@uarif What would you like to go for?

**Comment by tirthbha** [comment]
@uarif I think we should first focus on the github action implementation, right?

**Comment by uarif** [comment]
Okay, as you started the algorithm part, I will do the documentation one.

**Comment by tirthbha** [comment]
Sure!
